import type { FeedGroup } from '~/types/feed'

export default [{
    name: '高木同好',
    desc: '我们高木圈真是太有技术了.jpg',
    entries: [{
        author: 'Ice Year',
        sitenick: 'の位面',
        title: 'Ice Year の位面',
        desc: 'Il n\'y a pas de hasard, il n\'y a que des rendez - vous',
        link: 'https://blog.iceyear.eu.org/',
        feed: 'https://blog.iceyear.eu.org/index.xml',
        icon: 'https://blog.iceyear.eu.org/img/avatar_hu_a03d367ff590d53f.webp',
        avatar: 'https://blog.iceyear.eu.org/img/avatar_hu_a03d367ff590d53f.webp',
        archs: ['Hugo', 'Cloudflare'],
        date: '2023-08-15',
        comment: '高木圈同好，技术引路人，爱好Gal/折腾。',
    }, {
        author: '辰灿汐',
        sitenick: '的小站',
        title: '辰灿汐的小站',
        desc: '以自己的一切面对世间',
        link: 'https://aurorainic.top/',
        feed: 'https://aurorainic.top/feed',
        icon: 'https://pic.imgdb.cn/item/66be3143d9c307b7e9dbc86e.jpg',
        avatar: 'https://pic.imgdb.cn/item/66be3143d9c307b7e9dbc86e.jpg',
        archs: ['WordPress', '服务器'],
        date: '2022-09-20',
        comment: '高木圈同好/支柱，木创社创立者，技术方面也有不少探讨。',
    }, {
        author: 'WaterApple',
        title: '糖の小站',
        desc: '世界，您好！',
        link: 'https://waterapple09.com/',
        feed: 'https://waterapple09.com//feed',
        icon: 'https://cravatar.cn/avatar/5f8cf4ce23190a932b1995494e53f1c2?s=400&d=mp',
        avatar: 'https://cravatar.cn/avatar/5f8cf4ce23190a932b1995494e53f1c2?s=400&d=mp',
        archs: ['WordPress', '服务器'],
        date: '2023-06-20',
        comment: '高木圈同好，早期探索技术财务支持神秘大佬，对其敬意如涛涛洪水...',
    }, {
        author: '南栀',
        sitenick: 'Space',
        title: '南栀Space',
        desc: '葡萄何时才熟透，你要静候再静候。',
        link: 'https://blog.yoruzzz.cn//',
        feed: 'https://blog.yoruzzz.cn//feed',
        icon: 'https://blog.yoruzzz.cn/_next/image?url=https%3A%2F%2Fbu.dusays.com%2F2024%2F06%2F05%2F66605f9c7e600.jpg&w=640&q=75',
        avatar: 'https://blog.yoruzzz.cn/_next/image?url=https%3A%2F%2Fbu.dusays.com%2F2024%2F06%2F05%2F66605f9c7e600.jpg&w=640&q=75',
        archs: ['Mix Space', '服务器'],
        date: '2023-07-12',
        comment: '高木圈同好，初中生，技术折腾/生活都有交流。',
    }],
}, {
    name: '网上邻居',
    desc: '哔——啵——电波通讯中，欢迎常来串门。',
    entries: [{
        author: '晓空',
        sitenick: '空域',
        title: '晓空blog',
        desc: '探索更大的世界',
        link: 'https://blog.moeworld.tech/',
        feed: 'https://blog.moeworld.tech/feed/',
        icon: 'https://blog.moeworld.tech/wp-content/uploads/2024/08/cropped-favicon-32x32.png',
        avatar: 'https://blog.moeworld.tech/wp-content/themes/kratos-pjax-master/static/images/photo.jpg',
        archs: ['WordPress', '服务器'],
        date: '2024-02-25',
        comment: '技术折腾笔记。',
    }, {
        author: 'iMaeGoo',
        sitenick: '空间站',
        title: '虹墨空间站',
        desc: '虹墨空间站',
        link: 'https://www.imaegoo.com/',
        feed: 'https://www.imaegoo.com/atom.xml',
        icon: 'https://www.imaegoo.com/favicon.ico',
        avatar: 'https://www.imaegoo.com/images/avatar.jpg',
        archs: ['Hexo', '国内 CDN'],
        date: '2024-08-19',
        comment: '前端折腾，Twikoo评论系统作者。',
    }, {
        author: 'Kurococ Liu',
        desc: '被子外面很危险！',
        link: 'https://blog.lkurococ.top/',
        feed: 'https://blog.lkurococ.top/feed',
        icon: 'https://blog.lkurococ.top/_next/image?url=https%3A%2F%2Fcdn.lkurococ.top%2F2024%2F10%2F600292e5a454abe3b6e653801834fb60.jpg&w=384&q=75',
        avatar: 'https://blog.lkurococ.top/_next/image?url=https%3A%2F%2Fcdn.lkurococ.top%2F2024%2F10%2F600292e5a454abe3b6e653801834fb60.jpg&w=384&q=75',
        archs: ['Mix Space', '服务器'],
        date: '2024-08-20',
        comment: '学生，记录生活思考。',
    }, {
        author: 'AkiDay',
        desc: '永恒秋日之星',
        link: 'https://blog.akiday.com/',
        feed: 'https://blog.akiday.com/feed/',
        icon: 'https://blog.akiday.com/imgapi/profile.webp',
        avatar: 'https://blog.akiday.com/imgapi/profile.webp',
        archs: ['WordPress', '服务器'],
        date: '2024-08-20',
        comment: '目前仍在普通地读书。热爱物理，尤其是天文方向。',
    }, {
        author: '小雅',
        sitenick: '星辰角落',
        title: '星辰角落',
        desc: '热爱记录生活',
        link: 'https://ihello.cc',
        feed: 'https://ihello.cc/rss.xml',
        icon: 'https://s2.loli.net/2025/02/22/IYKOhlGQmz137jr.png',
        avatar: 'https://s2.loli.net/2025/02/22/IYKOhlGQmz137jr.png',
        archs: ['Halo', '服务器'],
        date: '2024-09-01',
        comment: '高中生，似乎终于找到了满意的记录生活（博客）工具',
    }, {
        author: '御坂秋生',
        sitenick: 'の小窝',
        title: '御坂秋生の小窝',
        desc: '不努力就只能听到别人的好消息',
        link: 'https://www.akio.top/',
        feed: 'https://www.akio.top/feed/',
        icon: 'https://webstatic.akio.top/user/NiuBoss123.jpg',
        avatar: 'https://webstatic.akio.top/user/NiuBoss123.jpg',
        archs: ['Mix Space', '服务器'],
        date: '2024-09-18',
        comment: '是落寞之人，是舰长，是旅行者，是开拓者，更是时刻陪伴你的朋友。',
    }, {
        author: '洛雨',
        sitenick: 'の小站',
        title: '洛雨の小站',
        desc: '历史终将证明一切',
        link: 'https://luotianyi.eu/',
        feed: 'https://luotianyi.eu/feed/',
        icon: 'https://luotianyi.eu/wp-content/uploads/2024/05/1715104252-v2-be101b87e6774cf029ce05ecff8f2b33_r-scaled-e1715104292489.jpg',
        avatar: 'https://luotianyi.eu/wp-content/uploads/2024/05/1715104252-v2-be101b87e6774cf029ce05ecff8f2b33_r-scaled-e1715104292489.jpg',
        archs: ['WordPress', '服务器'],
        date: '2024-10-02',
        comment: '超级喜欢洛天依~~~',
    }, {
        author: '千乐铃音',
        desc: '我在等风，也在等你。',
        title: '风月琉璃',
        link: 'https://miui.ink',
        feed: 'https://miui.ink/feed/',
        icon: 'https://miui.ink/wp-content/uploads/2023/11/im_1.jpg',
        avatar: 'https://miui.ink/wp-content/uploads/2023/11/im_1.jpg',
        archs: ['WordPress', '服务器'],
        date: '2024-10-18',
        comment: '是千乐铃音',
    }, {
        author: 'AI悦创',
        title: '别碰我的镜头盖',
        desc: '世界那么大，我想去看看',
        link: 'https://blog.bornforthis.cn/',
        feed: 'https://blog.bornforthis.cn/atom.xml',
        icon: 'https://bornforthis.cn/aiyc.svg',
        avatar: 'https://bornforthis.cn/aiyc.svg',
        archs: ['Hexo', '国内 CDN'],
        date: '2024-10-22',
        comment: '全栈工程师、私教老师、独立开发者、博主',
    }, {
        author: '星港',
        sitenick: 'Star☆',
        title: '❖星港◎Star☆',
        desc: '以博客记录生活与热爱！',
        link: 'https://blog.starsharbor.com/',
        icon: 'https://7.isyangs.cn/85/67b33ac68d72d-85.webp',
        avatar: 'https://7.isyangs.cn/85/67b33ac68d72d-85.webp',
        archs: ['Hexo', 'Vercel'],
        date: '2024-10-23',
        comment: '学生、计算机爱好者、博主',
    }],
}, {
    name: '友情链接',
    desc: '通常并非博客，但是依旧换了友链。',
    entries: [{
        author: '萌言Moey',
        sitenick: '一言',
        title: '萌言Moey',
        desc: '一个萌萌の句子收藏站',
        link: 'https://moey.cn/',
        // feed: 'https://blog.moeworld.tech/feed/',
        icon: 'https://pic.imgdb.cn/item/64a7c06e1ddac507ccdfe43f.jpg',
        avatar: 'https://pic.imgdb.cn/item/64a7c06e1ddac507ccdfe43f.jpg',
        archs: ['HTML', '国内 CDN'],
        date: '2024-02-25',
        comment: '一个一言站点，萌言萌句汇聚于此。',
    }, {
        author: '南蛮子懋和',
        sitenick: 'Dao',
        title: '南蛮子懋和',
        desc: '南蛮子懋和',
        link: 'https://www.dao.js.cn',
        feed: 'https://www.dao.js.cn/feed/',
        icon: 'https://img.dao.js.cn/zb_users/upload/2021/10/202110151634246697912592.png',
        avatar: 'https://img.dao.js.cn/zb_users/upload/2021/10/202110151634246697912592.png',
        archs: ['HTML', '国内 CDN'],
        date: '2024-08-19',
        comment: '李懋和，俗名李栋梁。书法、国画爱好者，互联网安全与前端建设者。',
    }],
}] satisfies FeedGroup[]
