name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repo
      uses: actions/checkout@v4

    - name: Setup Node.js and pnpm
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'pnpm'

    - name: Install dependencies with pnpm
      run: pnpm install

    - name: Build static files
      run: pnpm run generate

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: main
        folder: dist
        repository-name: PaloMiku/blog-public
        ssh-key: ${{ secrets.DEPLOY_KEY }}
